
name: Check PR

on:
  # Triggers the workflow on every pull request to master
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get App version
        id: version
#        shell: bash
        run: |
          echo "::set-output name=commits::$(git rev-list --count HEAD)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get color
        run: echo "The number of commits are ${{ steps.version.outputs.commits }}"

#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#
#      - name: Build with Gradle
#        run: ./gradlew build
#
#      - name: Run tests
#        run: ./gradlew test --stacktrace
